services:

  db:
    image: postgres:17
    restart: always

    container_name: mazegen-database-container

    shm_size: 128mb

    ports:
      - "5432:5432"

    environment:
#      POSTGRES_PASSWORD: ${DB_PASS} # todo: set in environment
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_DB: mazegen # name
      PGDATA: /var/lib/postgresql/data

    volumes:
      - mazegen-database:/var/lib/postgresql/data


  mazegen:
    image: vadimkliodt/mazegen
    container_name: mazegen-container
    build: .
    ports:
      - "8080:8080"
    restart: no # todo: change it

    depends_on:
      - db


volumes:
  mazegen-database:

