spring:
  application:
    name: MazeGen
    version: 1.0.0

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/andreev
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



logging:
  level:
    root: info
  pattern:
    dateformat: "HH:mm:ss"

